CREATE DATABASE LBYPRATAS;

CREATE TABLE USUARIO (
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  CPF CHAR(11) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  SENHA VARCHAR(255) NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE ITEM (
CODIGO_ITEM INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME VARCHAR(50) NOT NULL,
VALOR DECIMAL (8,2) NOT NULL,
QUANTIDADE INT NOT NULL
) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE ESTOQUE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO INT,
  ID_ITEM INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (ID_ITEM) REFERENCES ITEM(CODIGO_ITEM) 
    ON DELETE RESTRICT 
    ON UPDATE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;